// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3hjbQdAxaoEpFlo0DpofsDPMErhxLqUo',
    appId: '1:601389465276:web:f2a2a1778cc8790838dab9',
    messagingSenderId: '601389465276',
    projectId: 'easy-home-37f3c',
    authDomain: 'easy-home-37f3c.firebaseapp.com',
    storageBucket: 'easy-home-37f3c.appspot.com',
    measurementId: 'G-GLBV9XFEYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBaJAIilNykMlf89At_l-GDHC2R5wLRyk',
    appId: '1:601389465276:android:23ccb8908b0e68ac38dab9',
    messagingSenderId: '601389465276',
    projectId: 'easy-home-37f3c',
    storageBucket: 'easy-home-37f3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4fon5B1_7-JZwJQQ270c3TgyVVPlWQQg',
    appId: '1:601389465276:ios:a01d6bd7479ba68138dab9',
    messagingSenderId: '601389465276',
    projectId: 'easy-home-37f3c',
    storageBucket: 'easy-home-37f3c.appspot.com',
    iosClientId: '601389465276-dfd3rrf1d7bl744oreln9mrjdqjnq6ji.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4fon5B1_7-JZwJQQ270c3TgyVVPlWQQg',
    appId: '1:601389465276:ios:8e4929a5e49e295438dab9',
    messagingSenderId: '601389465276',
    projectId: 'easy-home-37f3c',
    storageBucket: 'easy-home-37f3c.appspot.com',
    iosClientId: '601389465276-g4m9ro74uvbeip0r3qscemqjmjgiqvj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyHome.RunnerTests',
  );
}
